config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'pages#index'


get "/categories/:id", to: "tours#categories", as: "categories" 	 

  devise_for :users

resources :tours

resources :orders

resources :userparams

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tours
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	 validates :firstname, :lastname, :from_city, :to_city, :count, :data, :user_id, presence: true
end

app/models/tour.rb
class Tour < ApplicationRecord
	belongs_to :user
	belongs_to :category
	validates :title, :body, :shortbody, :category, presence:true	
end

app/models/tourcomment.rb
class Tourcomment < ApplicationRecord
		belongs_to :user
	    belongs_to :tour
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :userparam, dependent: :destroy

  has_many :tours
  has_many :orders
         
end

app/models/userparam.rb
class Userparam < ApplicationRecord
	 belongs_to :user
  
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", small: "50x50>" }, default_url: "/images/avatar.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new
  	@order = Order.new
  end

  def create
     @order = current_user.orders.build(order_params)
	  if @order.save
			redirect_to order_path(current_user.userparam.id)
		else render 'new'
		end
  end

  def show
    @user = Userparam.find(current_user.userparam.id)
  end

  private

  def order_params
  	params.require(:order).permit(:firstname, :lastname, :from_city, :to_city, :count, :data, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index 
  	@users = User.all
  	@tours = Tour.all
  end
end

app/controllers/tourcomments_controller.rb
class TourcommentsController < ApplicationController

	def create
		params[:tourcomment][:tour_id] = params[:tour_id]
		params[:tourcomment][:user_id] = current_user.id
		@tourcomment = Tourcomment.create(tourcomments_params)
		if @tourcomment.save
			redirect_to tour_path(params[:tour_id])
		else
			@tourcomment.errors.full_messages.each do |msg|
				@msg = msg
		end  
    	flash[:notice] = "#{@msg}"
    	redirect_to tour_path(params[:tour_id])
	    end
	    
	end


	private
	def tourcomments_params
		params.require(:tourcomment).permit(:user_id, :tour_id, :textofcom)
	
	end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
    before_action :authenticate_user!, exist:[:show]
    before_action :set_tour, only:[:show]
  def index
  end

  def new
  	@tour = Tour.new
  end

  def create
    if current_user.role == "Editor"
     params[:tour][:category_id]=params[:category_id]
     @tour = current_user.tours.build(tour_params)
    if @tour.save
      redirect_to root_path
    else render 'new'
    end
    end
  end


  def show
  end

  def category
    pp @tours=Tour.where(category_id: params[:id])
  end



  private

  def tour_params
  	params.require(:tour).permit(:title, :shortbody, :body, :price, :category_id, :user_id)
  end

  def set_tour
    @tour=Tour.find(params[:id])
  end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
before_action :authenticate_user!
before_action :get_userparam, except: [:new, :create]


  def index
    if @userparam.nil?
      redirect_to new_userparam_path
    else
      redirect_to userparam_path(@userparam.id)
    end
  end

  def show
    @user = Userparam.find(current_user.userparam.id)
  end

  def new
    @userparam = Userparam.new
  end

  def create
    @userparam = current_user.build_userparam(userparams_params)
    if @userparam.save
      redirect_to userparam_path(@userparam.id)
    end
  end

  def edit
  end


  def update
    @userparam.update(userparams_params)
    redirect_to userparam_path(@userparam.id)
  end

private

  def userparams_params
    params.require(:userparam).permit(:user_id, :firstname, :lastname, :country, :city, :phone, :avatar)
  end

  def get_userparam
    @userparam = Userparam.find_by(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tourcomments_helper.rb
module TourcommentsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/layouts/_footer.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->




<section class="index-link">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="link-area">
                    <h3>ABOUT US</h3>
                    <P>Building Consensus among your Senior leaders to leverage your digital strengths and work on gaps which are hindering your growth.</P>
                </div>
            </div>
            <div class="col-md-3">
                <div class="link-area">
                    <h3>PRODUCT</h3>
                    <ul>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="link-area">
                    <h3>COMPANY</h3>
                    <ul>
                    <li><a href="#"> Home</a></li>
                    <li><a href="#"> Blog</a></li>
                    <li><a href="#"> About</a></li>
                    <li><a href="#"> contact</a></li>
                    <li><a href="#"> Jobs</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="link-area">
                    <h3>LEARM MORE</h3>
                    <ul>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="index-social">
    <div class="container">
    <div class="row index-social-link text-center">
        </div>
        </div>
</section>

app/views/layouts/_footer.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->




<section class="index-link">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="link-area">
                    <h3>ABOUT US</h3>
                    <P>Building Consensus among your Senior leaders to leverage your digital strengths and work on gaps which are hindering your growth.</P>
                </div>
            </div>
            <div class="col-md-3">
                <div class="link-area">
                    <h3>PRODUCT</h3>
                    <ul>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="link-area">
                    <h3>COMPANY</h3>
                    <ul>
                    <li><a href="#"> Home</a></li>
                    <li><a href="#"> Blog</a></li>
                    <li><a href="#"> About</a></li>
                    <li><a href="#"> contact</a></li>
                    <li><a href="#"> Jobs</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="link-area">
                    <h3>LEARM MORE</h3>
                    <ul>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    <li><a href="#"> Services-1</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="index-social">
    <div class="container">
    <div class="row index-social-link text-center">
        </div>
        </div>
</section>

app/views/layouts/_navbar.html.erb
<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Travel</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/tours/new ">Add Tour</a>
                    </li>
                    <li>
                        <a href="/orders/new">Order Tour</a>
                    </li>
                    <li>
                        <a href="/userparams">Userparam</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="/categories/:id " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categories
                        </a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">Europe</a></li>
                        <li><a href="#">Mountain travel</a></li>
                        <li><a href="#">Spa travel</a></li>
                        <li><a href="#">See travel</a></li>
                        <li><a href="#">Asia travel</a></li>
                    </ul>
                    </li>
                </ul>
                <% if current_user.nil? %>
                  <%= link_to user_session_path do %>
                    <ul class="nav navbar-nav navbar-right" style="margin-top: 15px; color: #bcc0c4; ">
                       Login 
                    </ul>
                <%end%>
                <% else %>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                    <ul class="nav navbar-nav navbar-right" style="margin-top: 15px; color: #bcc0c4;">
                      Logout
                    </ul>
                <%end%>
                <% end %>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar'%>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/orders/new.html.erb
<div class="main">
  <div class="container my-container">
    <div class="content">
        <h1>Orders</h1>
        <%= form_for @order do |f| %>
        <div class="row">
          <div class="col-md-4">
              <div class="form-group">
                  <%= f.label :firstname %>
                  <%= f.text_field :firstname, class: 'form-control' %>
              </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
                  <%= f.label :lastname %>
                  <%= f.text_field :lastname, class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
            <p><%= f.label "count"  %></p>
            <%= f.select :count, ['1','2','3'], class: 'form-control' %><br />
          </div>
            </div>
          </div>
        <div class="row">
          <div class="col-md-3">
                  <%= f.label :from_city %>
                  <%= f.text_field :from_city, class: 'form-control' %>
          </div>
          <div class="col-md-3">
                  <%= f.label :to_city %>
                  <%= f.text_field :to_city, class: 'form-control' %>
          </div>
          <div class="col-md-3">
                  <%= f.label :data %>
                  <%= f.text_field :data, class: 'form-control', type: 'date', placeholder: 'date'  %>
          </div>
          <div class="col-md-3">
            <div class="form-group" style="margin-top: 27px;" align="right">
             <%= f.submit 'Зберегти', class: 'btn btn-primary' %>
             <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
            </div>
          </div>
        </div>
      </div>


      <%end%>
      </div>    
    </div>
</div>

app/views/orders/show.html.erb
<div class="main">
  <div class="container my-container">
    <div class="content">
    	<div class="flex-container">

    		<div>
	    		<h1><%= @user.firstname %> Profile</h1>

				Firstname: <%= @user.firstname %><br />
				Lastname: <%= @user.lastname %><br />
				Country: <%= @user.country %><br />
				City: <%= @user.city %><br />
				Phone: <%= @user.phone %><br />
    		</div>

			<div class="avatar">
    		<h1>Дякую за замовлення</h1>
				 <%= image_tag(@user.avatar, height: '100', width: '100') %><br />
				</div>


    	</div>


	<%= link_to "Edit Profile", edit_userparam_path %>
	</div>
  </div>
</div>

app/views/pages/index.html.erb
    <!-- Full Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active">
          <div class="fill" id="item1"></div>
            </li>
            <li data-target="#myCarousel" data-slide-to="1">
              <div class="fill" id="item2"></div>
            </li>
            <li data-target="#myCarousel" data-slide-to="2">
              <div class="fill" id="item3"></div>
            </li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" id="image1"></div>
            </div>
            <div class="item">
                <div class="fill" id="image3"></div>
            </div>
            <div class="item">
                <div class="fill" id="image2"></div>
            </div>
        </div>

    </header>


<h1>Pages#index</h1>


<% @tours.each do |tour| %>
    <%= render 'tours/tour', tour:tour %>
<%end%>

app/views/tours/_form.html.erb
<%= form_for @tour do |f| %>

<p><%= f.label :category %></p>
<%= select_tag 'category_id', options_from_collection_for_select(Category.all, 'id', 'name')%>


<div class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
   <%= f.label :shortbody %>
   <%= f.text_area :shortbody, class: 'form-control' %>
</div>

<div class="form-group">
   <%= f.label :body %>
   <%= f.text_area :body, class: 'form-control' %>
</div>


<div class="form-group">
   <%= f.label :price %>
   <%= f.text_field :price, class: 'form-control' %>
</div>

<div class="form-group">
   <%= f.submit 'Зберегти', class: 'btn btn-primary' %>
     <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>

<% end %>

app/views/tours/_tour.html.erb
<div class="border" style=" outline: 1px groove #010;">

	<h3><%=link_to tour.title, tour_path(tour.id) %></h3>
<small>
			<time><%= tour.created_at.to_date.strftime("%d %B, %Y") %></time>
</small>
<p><%= tour.shortbody %></p>

</div>

app/views/tours/categories.html.erb
<div align="center">
<% @tours.each do |tour|%>
<%= render 'tours/tour', tour:tour %>
<%end%>
</div>

app/views/tours/new.html.erb
<div class="main main_height">
  <div class="container my-container ">
    <div class="content">
		<h2>Додати новий тур</h2>
		<%= render 'form' %>
  </div>
  </div>
</div>

app/views/tours/show.html.erb
<div class="main main_height">
  <div class="container my-container ">
    	<div class="content">
    	<h1 align="center"><%= @tour.title %></h1>
			<div class="col-md-12" style="text-align: justify;">
				<p>Опис: <%=@tour.shortbody %></p>
				<%= @tour.body%>
			</div>
			price : <%= @tour.price%>

		</div>
	</div>
</div>

app/views/userparams/_form.html.erb
<div class="main">
  <div class="container my-container">
    <div class="content">
      <div class="form-group">
   <%= f.text_field :firstname, placeholder: "First name", autofocus: true, class:'form-control' %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :lastname, placeholder: "Last name", class:'form-control' %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :country, placeholder: "Country", class:'form-control' %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :city, placeholder: "City", class:'form-control' %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :phone, placeholder: "Phone number", class:'form-control' %>    
  </div>
  
  <div class="form-group text-center m-t-30">
    <%= f.submit "Save", class: "btn btn-info" %>
  </div>
 
  </div>
  </div>
</div>

app/views/userparams/edit.html.erb
<%= form_for @userparam, validate: true, url: userparam_path(@userparam.id), method: :patch do |f| %>

<%= render 'form', f: f %>
  
<% end %>

app/views/userparams/new.html.erb
<%= form_for @userparam, url: userparams_path, validate: true do |f| %>

<%= render 'form', f: f %>
 
<% end %>

app/views/userparams/show.html.erb
<div class="main">
  <div class="container my-container">
    <div class="content">
    	<div class="flex-container">
    		<div>
	    		<h1><%= @user.firstname %> Profile</h1>

				Firstname: <%= @user.firstname %><br />
				Lastname: <%= @user.lastname %><br />
				Country: <%= @user.country %><br />
				City: <%= @user.city %><br />
				Phone: <%= @user.phone %><br />
    		</div>

			<div class="avatar">
				 <%= image_tag(@user.avatar, height: '100', width: '100') %><br />
				</div>


    	</div>


	<%= link_to "Edit Profile", edit_userparam_path %>
	</div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>